# Generated by Django 3.1.7 on 2021-03-13 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('project', models.CharField(choices=[('web-app', 'WEB APP'), ('mobile-app', 'MOBILE APP'), ('machine-learning', 'MACHINE LEARNING'), ('ai', 'AI'), ('deep-learning', 'DEEP LEARNING')], default='web-app', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start', models.DateTimeField(null=True)),
                ('finish', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
